import type { Metadata } from "next";
import { Menu } from "@/common/components/Menu/Menu";
import "../styles/globals.scss";
import { roboto } from "@/styles/font";

export const metadata: Metadata = {
  title: "Layout Next.js Title",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.variable}`}>
        <Menu />
        <main className="main-container">{children}</main>
      </body>
    </html>
  );
}
